[package]
name = "mwe"
version = "0.1.0"
authors = ["azzamsa <vcs@azzamsa.com>"]
edition = "2021"

[dependencies]
axum = "0.6.1"
tokio = { version = "1.23.1", features = ["macros", "rt-multi-thread"] }

# GraphQL
async-graphql = { version = "5.0.5" }
async-graphql-axum = "5.0.5"
