[package]
name = "mwe"
version = "0.1.0"
authors = ["azzamsa <vcs@azzamsa.com>"]
edition = "2021"

[dependencies]
axum = "0.6.20"
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread"] }

# GraphQL
async-graphql = { version = "6.0.7" }
async-graphql-axum = "6.0.7"
