# This file is used for local environment

version: "3"
services:

  db:
    image: docker.io/postgres:15
    restart: always
    ports:
      - 5432:5432
    volumes:
      # Use `:Z` in SELinux-enabled disro.
      - ./cdata/db:/var/lib/postgresql/data/:Z
    environment:
      POSTGRES_USER: durin
      POSTGRES_PASSWORD: SpeakFriendAndEnter
      POSTGRES_DB: mwe
