#!/usr/bin/env -S just --justfile

alias d := dev
alias r := run
alias f := fmt

# List available commands.
_default:
    just --list --unsorted

# Setup the repository.
setup:
    cargo-install 'bacon'

# Tasks to make the code-base comply with the rules. Mostly used in git hooks.
comply: fmt lint

# Check if the repository comply with the rules and ready to be pushed.
check: fmt-check lint

# Develop the app.
dev:
    bacon clippy

# Run the app.
run:
    cargo run --quiet

# Run the container.
image-start service="":
    podman-compose up {{ service }} -d

# Stop the container.
image-stop:
    podman-compose down

# Restart the containers.
image-restart:
    just image-stop
    just image-run

# Format the codebase.
fmt:
    cargo fmt --all

# Check is the codebase properly formatted.
fmt-check:
    cargo fmt --all -- --check

# Lint the codebase.
lint:
    cargo clippy --all-targets --all-features
