[package]
name = "mwe"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

aws-config = "0.56.1"
aws-sdk-s3 = "0.31.2"
aws-types = "0.56.1"
http = "0.2.9"
